<!DOCTYPE html>
<html>
<head>
    <title>PHP Test</title>
</head>
<body>
    <?php
    $nome = "João";
    echo '<h1>Welcome to PHP!</h1>';
    echo '<p>This is a paragraph generated by PHP.</p>';
    echo '<div class="echos">' . $nome . '</div>';
    ?>

<style>
        .echos {
            color: red;
            font-weight: bold;
        }
    </style>
</body>
</html>